#!/usr/bin/env python3

import argparse
from cookie_logic import *

def main():
    parser = argparse.ArgumentParser(prog="most_active_cookie.py", \
                                    description='Return the most active cookies for a specified day.')
    parser.add_argument('log_file', type=str, help='Path to the cookie log file')
    parser.add_argument('-d', '--date', type=str, required=True, \
                        help='Date for which to find the most active cookie, in YYYY-MM-DD format')

    args = parser.parse_args()

    if len(args.date) != 10:
            raise AssertionError("Input date not in YYYY-MM-DD format")

    print(getActiveCookieFile(args.log_file, args.date))

if __name__ == "__main__":
    main()